version: "3.8"

services:
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/api/src
      - ./api/nodemon.json:/home/node/api/nodemon.json
    container_name: ts-node-docker
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run dev
    depends_on:
      - mysql_server
    networks:
      - back-end

  mysql_server:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./sql/createDb.sql:/docker-entrypoint-initdb.d/createDb.sql"
      - "./sql/insertData.sql:/docker-entrypoint-initdb.d/insertData.sql"
      - "./sql/insertDataSchLect.sql:/docker-entrypoint-initdb.d/insertDataSchLect.sql"
      - "./sql/insertDataSchRooms.sql:/docker-entrypoint-initdb.d/insertDataSchRooms.sql"
      - "./sql/insertDataSchCourses.sql:/docker-entrypoint-initdb.d/insertDataSchCourses.sql"
    networks:
      - back-end
    environment:
      - MYSQL_DATABASE=scheduleDb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=parool
      - MYSQL_ROOT_PASSWORD=parool
      - LANG=C.UTF-8

networks:
  back-end:
    driver: bridge
volumes:
  ignore:
